// @ts-check
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const parser = await readFile(path.join(root, 'src/parser.c'), 'utf8');
const predicates = [1, 2].map((index) => {
  const match = parser.match(
    new RegExp(`\\b(ts_lex_\\w+\\(ts_lex_sym_identifier_character_set_${index}_ascii,[^\\n;]*?lookahead\\))`)
  );
  assert.ok(match?.[1], `Missing generated identifier predicate ${index}`);
  return match[1];
});
await mkdir(path.join(root, '.tmp'), { recursive: true });
const temporary = await mkdtemp(path.join(root, '.tmp/identifier-ranges-'));
try {
  const source = path.join(temporary, 'ranges.c');
  const executable = path.join(temporary, 'ranges');
  await writeFile(
    source,
    `
#include <stdio.h>
#include <stdlib.h>
#include ${JSON.stringify(path.join(root, 'src/parser.c'))}

// Only character predicates are evaluated; a scanner call is a generator bug.
void *tree_sitter_c_external_scanner_create(void) { abort(); }
void tree_sitter_c_external_scanner_destroy(void *payload) { abort(); }
bool tree_sitter_c_external_scanner_scan(void *payload, TSLexer *lexer, const bool *valid) { abort(); }
unsigned tree_sitter_c_external_scanner_serialize(void *payload, char *buffer) { abort(); }
void tree_sitter_c_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) { abort(); }

int main(void) {
  for (int table = 0; table < 2; table++) {
    printf("static const TSCharacterRange preproc_identifier_%s[] = {\\n", table ? "continue" : "start");
    int32_t start = -1;
    unsigned column = 0;
    for (int32_t lookahead = 0; lookahead <= 0x110000; lookahead++) {
      bool member = lookahead < 0x110000 && (table ? ${predicates[1]} : ${predicates[0]});
      if (member && start < 0) start = lookahead;
      if (!member && start >= 0) {
        printf("%s{0x%x, 0x%x},%s", column ? " " : "  ", (unsigned)start, (unsigned)(lookahead - 1), column == 7 ? "\\n" : "");
        column = (column + 1) % 8;
        start = -1;
      }
    }
    printf("%s};\\n\\n", column ? "\\n" : "");
  }
}
`
  );
  execFileSync('cc', ['-std=c11', '-I', path.join(root, 'src'), source, '-o', executable]);
  const tables = execFileSync(executable, { encoding: 'utf8' });
  await writeFile(
    path.join(root, 'src/identifier.h'),
    `// Generated by script/generateIdentifierRanges.js from the parser's Unicode identifier predicates.
#ifndef TREE_SITTER_C_IDENTIFIER_H_
#define TREE_SITTER_C_IDENTIFIER_H_

#include "tree_sitter/parser.h"

${tables}#endif
`
  );
} finally {
  await rm(temporary, { recursive: true, force: true });
}
