import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';

const parser = await readFile(new URL('../src/parser.c', import.meta.url), 'utf8');
const tables = [1, 2].map((index) => {
  const match = parser.match(
    new RegExp(`static const TSCharacterRange sym_identifier_character_set_${index}\\[\\] = {([\\s\\S]*?)\n};`)
  );
  assert.ok(match, `Missing generated identifier character set ${index}`);
  return match[1];
});
assert.ok(!tables[0].includes("{'0', '9'}") && tables[1].includes("{'0', '9'}"));
await writeFile(
  new URL('../src/identifier.h', import.meta.url),
  `// Generated by script/generateIdentifierRanges.js from the parser's Unicode identifier tables.
#ifndef TREE_SITTER_C_IDENTIFIER_H_
#define TREE_SITTER_C_IDENTIFIER_H_

#include "tree_sitter/parser.h"

static const TSCharacterRange preproc_identifier_start[] = {${tables[0]}
};
static const TSCharacterRange preproc_identifier_continue[] = {${tables[1]}
};

#endif
`
);
